<a href="https://colab.research.google.com/github/roshika1235/Data_Analysis_Tasks/blob/main/Loan_approval_svm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data analysis in load_approval dataset

## import all necessary libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

## EXPLORE DATASET

In [ ]:
df=pd.read_csv("/content/loan_data.csv")
df

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,male,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,male,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,male,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [ ]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

person_age                        0
person_gender                     0
person_education                  0
person_income                     0
person_emp_exp                    0
person_home_ownership             0
loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [ ]:
df.drop({'person_gender','person_age','person_education'},axis=1,inplace=True)

## CHANGING CATEGORICAL VALUES INTO NUMBERICAL

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['person_home_ownership']=le.fit_transform(df['person_home_ownership'])
df['loan_intent']=le.fit_transform(df['loan_intent'])
df['previous_loan_defaults_on_file']=le.fit_transform(df['previous_loan_defaults_on_file'])

## EDA and DATA VISUALIZATION

In [ ]:
sns.countplot(df['person_home_ownership'],hue=df['loan_status'])

## MODEL TRAINING

In [ ]:
x=df.drop('loan_status',axis=1)
y=df['loan_status']

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
# from sklearn.preprocessing import StandardScaler
# sc=StandardScaler()
# xtrain=sc.fit_transform(xtrain)

In [ ]:
model=SVC()
model.fit(xtrain,ytrain)

SVC()

In [ ]:
ypred=model.predict(xtest)
ypred

array([0, 0, 0, ..., 0, 0, 0])

## PERFORMANCE METRICS

In [ ]:
print("confusion_matrix: ", confusion_matrix(ytest,ypred))
print("accuracy_score: ", accuracy_score(ytest,ypred))
print("classification_report: ", classification_report(ytest,ypred))

confusion_matrix:  [[6861   61]
 [1768  310]]
accuracy_score:  0.7967777777777778
classification_report:                precision    recall  f1-score   support

           0       0.80      0.99      0.88      6922
           1       0.84      0.15      0.25      2078

    accuracy                           0.80      9000
   macro avg       0.82      0.57      0.57      9000
weighted avg       0.80      0.80      0.74      9000

## IT IS WORKING WELL , BUT

In [13]:
print("training_eff:",model.score(xtrain,ytrain))
print("testing_eff:",model.score(xtest,ytest))

training_eff: 0.8046666666666666
testing_eff: 0.7967777777777778

## NEW PREDICTION

In [14]:
new_data=df.iloc[:1, :-1]
# new_data=sc.transform(new_data)
model.predict(new_data)

array([1])